name: release

on: 
  push:
    tags:
      - '*'

jobs:
  release-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Install OpenMCT
        run: npm ci
        working-directory: web/
      - name: Build OpenMCT bundle
        run: npm run build
        working-directory: web/
      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.21
          dest: build
          prefix: gotelem-full
          targets: windows/amd64,linux/amd64,linux/arm64,linux/arm/v7,darwin/arm64,darwin/amd64
          tags: openmct
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
      - name: Release binaries
        uses: https://gitea.com/actions/release-action@main
        with:
          files: |-
            build/**
          api_key: '${{secrets.RELEASE_TOKEN}}'
