name: Node.js CI

on:
  push:
    paths:
      - "web/**"

jobs:
  build-openmct:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npx eslint .

